### PR TITLE
Support extended crontabs that specify year and second

### PR DESCRIPTION
**Pull request by mtrudel**
Similar to support for extended crontabs in https://github.com/jshmrtn/crontab/, this allows crontabs to optionally be seven segments long, in the format:

```
      * * * * * * *
      | | | | | | |
      | | | | | | +-- :year Year                 (range: 1900-3000)
      | | | | | +---- :weekday Day of the Week   (range: 1-7, 1 standing for Monday)
      | | | | +------ :month Month of the Year   (range: 1-12)
      | | | +-------- :day Day of the Month      (range: 1-31)
      | | +---------- :hour Hour                 (range: 0-23)
      | +------------ :minute Minute             (range: 0-59)
      +-------------- :second Second             (range: 0-59)
```

Existing 5 segment crontabs are unaffected.

### CODE REVIEW

**Comment by oscar123mendoza** [comment]
Whats the status here?

**Comment by mtrudel** [comment]
AFAIC it's still current - failing CI seems to be unrelated (it's an error with rake from the looks of it). We've been using this branch in production for several months without issue.

**Comment by stakach** [comment]
I'd be interested in seeing this merged too.
If it's a matter of maintenance, I'd be happy to come on as a maintainer.

**Comment by oscar123mendoza** [comment]
@mtrudel @stakach https://github.com/mtrudel/parse-cron/compare/master...oscar123mendoza:master

I incorporated some changes on top of these also. I have the gem here: https://packagecloud.io/oscar123mendoza/gems

**Pull request closed without merging**
